profile_id: base
version: 1.0.0
status: active

meta:
  id: base_v1
  description: "Perfil base agnostico para preguntas con evidencia"
  owner: "orchestrator-core"

identity:
  role: "Analista tecnico agnostico"
  tone: "Formal, preciso y basado en evidencia"
  style_guide:
    - "Usa listas planas para hallazgos concretos."
    - "Indica explicitamente cuando una afirmacion es inferencia."

domain_entities:
  - evidencia
  - fuente
  - requisito

synthesis:
  system_persona: >-
    Eres un analista tecnico agnostico. Responde solo con evidencia recuperada.
  citation_format: C#/R#
  strict_subject_label: Afirmacion
  strict_reference_label: Referencia
  identity_role_prefix: Rol operativo
  identity_tone_prefix: Tono
  strict_system_prompt_template: >-
    Responde SOLO con evidencia del CONTEXTO. Cada afirmacion clave debe incluir
    al menos una cita con marcadores exactos con el formato '{citation_format}'
    tal como aparecen en el CONTEXTO. Si no hay evidencia suficiente, dilo
    explicitamente.
  interpretive_system_prompt_template: >-
    Responde solo con evidencia del CONTEXTO. Puedes conectar evidencias entre
    fuentes, pero cada afirmacion relevante debe incluir al menos una referencia
    con formato '{citation_format}' y no debes inventar contenido.
  strict_style_template: |-
    FORMATO:
    1) Para cada afirmacion clave: {strict_subject_label} | Cita literal breve | {strict_reference_label}.
    2) No inventes referencias ni texto fuente.
  interpretive_style_template: |-
    Estructura recomendada:
    - Hallazgo principal respaldado por evidencia.
    - Implicaciones operativas y tecnicas.
    - Riesgos o vacios de evidencia detectados.
    - Integracion entre fuentes y conclusion.
    Incluye referencias ({citation_format}) al final de cada punto.
  user_prompt_template: |-
    PREGUNTA:
    {query}

    CONTEXTO:
    {context}

    {style}
  synthesis_rules:
    - Cada afirmacion relevante debe tener soporte en el contexto recuperado.
    - Si no existe evidencia suficiente, dilo explicitamente.
    - No inventes fuentes ni requisitos.
  strict_style:
    - "Para cada afirmacion: requisito | cita breve | fuente."
    - "Si falta evidencia: No encontrado explicitamente en el contexto recuperado."
  interpretive_style:
    - Puedes conectar evidencias separadas, pero marca cuando sea inferencia.
    - Incluye referencias al final de cada punto.

router:
  literal_list_hints: [entradas, salidas, lista, enumera, listado]
  literal_normative_hints: [clausula, obligatorio, exacto, literal, "que exige"]
  comparative_hints: [compar, difer, vs, ambas, respecto]
  interpretive_hints: [implica, impacto, analice, interaccion, por que]
  conflict_markers: [conflicto, confidencial, denuncia, represalia]
  evidence_markers: [evidencia, trazabilidad, verificar, registros]
  scope_hints: {}
  scope_patterns: []
  reference_patterns:
    - "\\b\\d+(?:\\.\\d+)+\\b"
  complexity_patterns:
    - "\\b(?:analiza|relacion|relación|impact|compara|calcula|calcular|extrae|extraer|formula)\\b"
  extraction_patterns:
    - "\\b(?:extrae|extraer|estructura|json|tabla|reactivo|insumo|cantidad|bom)\\b"
  calculation_patterns:
    - "\\b(?:calcula|calcular|cuanto|cuánto|formula|lote|muestras)\\b"

clarification_rules: []

query_modes:
  default_mode: explanatory_response
  modes:
    literal_list_extract:
      require_literal_evidence: true
      allow_inference: false
      retrieval_profile: literal_lista
      tool_hints: [semantic_retrieval, structural_extraction, citation_validator]
    literal_clause_check:
      require_literal_evidence: true
      allow_inference: false
      retrieval_profile: literal_normativa
      tool_hints: [semantic_retrieval, citation_validator]
    cross_scope_analysis:
      require_literal_evidence: false
      allow_inference: true
      retrieval_profile: comparativa
      tool_hints: [semantic_retrieval, logical_comparison, citation_validator]
    scope_clarification:
      require_literal_evidence: true
      allow_inference: false
      retrieval_profile: ambigua_scope
      tool_hints: [citation_validator]
    explanatory_response:
      require_literal_evidence: false
      allow_inference: true
      retrieval_profile: explicativa
      tool_hints: [semantic_retrieval, citation_validator]
  intent_rules:
    - id: base_literal_list
      mode: literal_list_extract
      any_keywords: [lista, enumera, listado, vinetas]
    - id: base_literal_clause
      mode: literal_clause_check
      any_keywords: [clausula, literal, exacto, textualmente, cita, que exige]
      any_patterns:
        - "\\b\\d+(?:\\.\\d+)+\\b"
    - id: base_cross_scope
      mode: cross_scope_analysis
      any_keywords: [compar, difer, vs, entre, respecto, impacto]
    - id: base_scope_ambiguity
      mode: scope_clarification
      any_markers: ["__mode__=ambigua_scope"]

retrieval:
  min_score: 0.75
  search_hints: []
  by_mode:
    literal_lista:
      chunk_k: 45
      chunk_fetch_k: 220
      summary_k: 3
      require_literal_evidence: true
    literal_normativa:
      chunk_k: 45
      chunk_fetch_k: 220
      summary_k: 3
      require_literal_evidence: true
    comparativa:
      chunk_k: 35
      chunk_fetch_k: 140
      summary_k: 5
      require_literal_evidence: false
    ambigua_scope:
      chunk_k: 0
      chunk_fetch_k: 0
      summary_k: 0
      require_literal_evidence: true
    explicativa:
      chunk_k: 30
      chunk_fetch_k: 120
      summary_k: 5
      require_literal_evidence: false

capabilities:
  reasoning_level: low
  allowed_tools:
    - semantic_retrieval
    - citation_validator
  reasoning_budget:
    max_steps: 4
    max_reflections: 2
  tool_policies:
    python_calculator:
      enabled: false

validation:
  require_citations: true
  forbidden_concepts: []
  fallback_message: "No tengo informacion suficiente en el contexto para responder."
